#include <iostream>

/**
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
* By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(int argc, char const *argv[])
{
  int prev = 1, next = 1, sum = 0, temp, max = 4000000;

  while(next < max)
  {
    temp = next;
    next += prev;
    prev = temp;

    if(next >= max)
    {
      break;
    }

    if(next % 2 == 0)
    {
      sum += next;
    }
  }
  std::cout << "\nThe total is: " << sum << std::endl;
  return 0;
}